### ISSUE TITLE
How to remove disappear animation?

### ISSUE THREAD

**Issue by RusseII** [react-component/texty#34]
Is there a way to stop the disappear animation from happening when the text inside the <Texty/> component changes? 

example of weird behavior:
https://codesandbox.io/embed/react-example-g8r91

**Comment by jljsj33** [comment]
That's a problem. Think about it later. However, switching text is not recommended. It can be used in conjunction with `rc-queue-anim`.

[![Edit React example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-example-gvwmx?fontsize=14)

**Comment by RusseII** [comment]
Thanks @jljsj33 - you are the best!
